### ISSUE TITLE
Error when sending test mail

### ISSUE THREAD

**Issue by insuusvenerati** [mriedmann/humhub-docker#158]
I'm getting an error when trying to change the email that's used to send mail from Humhub when using the docker container at version 1.6.2.

`humhub_1   | [30-Nov-2020 23:18:44] WARNING: [pool www] child 32 said into stderr: "sendmail: can't connect to remote host (127.0.0.1): Connection refused"`

PHP is set as the mail transport type. Is SMTP required to get mail working correctly or am I doing something wrong here?

**Comment by jvies** [comment]
hello,

I think there is some issue due to caching. To check the value you configured in the smtp configuration form, you have to check the content of the file config/dynamic.php, where you should find something like :
`'mailer' => 
    array (
      'transport' => 
      array (
        'class' => 'Swift_SmtpTransport',
        'host' => 'mysmtp.org',
        'username' => 'mysmtpuser',
      ),
    ),
`

**Comment by jimlinntu** [comment]
@insuusvenerati  I encountered the same issue. Have you solved it?

**Comment by mriedmann** [comment]
It as actually no real "bug". The problem here is, that alpine does not include a "traditional" sendmail server but only a relay dependent version. Sending mail directly from your server (without a proper configured smtp server will be flagged as spam in most cases anyways). I see 2 easy solutions to this:
1. Use something like sendgrid (https://sendgrid.com/pricing/). It offers you a smtp-relay server with 100 mails for free per day and can be used with the SMTP setting.
2. Setup your own SMTP server in a separate container (e.g. postfix) or on a small virtual server. There you can set the right dns settings to avoid being flagged as "spam".
3. If you just need to see the mails for testing, look at the `mailcatch` container (https://github.com/mriedmann/humhub-docker/blob/master/docker-compose.yml#L57). It provides a basic WebUI that shows all mails it receives. 

Installing and running a SMTP server inside the container would raise the resource usage and complexity significantly without providing much benefit. Today few people are directly sending mail over there own SMTP servers and that's a good thing (to avoid spam). For more information on that topic see the following link:
https://stackoverflow.com/questions/45497512/how-to-get-sendmail-working-in-alpine-docker-container

**Comment by jimlinntu** [comment]
@mriedmann Thank you so much!
I am newbie to smtp, your reply is really informative!

**Comment by mriedmann** [comment]
I will close this for now. Feel free to comment on that issue or open a new one if something comes up again.
