### ISSUE TITLE
version 2.5

### ISSUE THREAD

**Issue by Giovenale2** [mriedmann/humhub-docker#36]
Hi,
I am trying to use your image on docker for synology. Version 1.0.1 works, but version 2.5 does not. I follow your quick start instructions, I get to the first configuration page, but when I click "next" the page remains stuck in loading and the log keeps recording the same message:

2018-05-10 04:50:03 | stdout | IP - - [10/May/2018:04:50:03 +0000] "GET /index.php?r=installer%2Findex&_pjax=%23layout-content&_=1525927784576 HTTP/1.1" 302 5 "http://local:port/index.php?r=installer%2Findex%2Fgo" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15" "-"
-- | -- | --
2018-05-10 04:50:03 | stdout | - -  10/May/2018:04:50:03 +0000 "GET /index.php" 302

This happens with Chorme and with Safari as well. 
Is there any known issue about this?

**Comment by mriedmann** [comment]
Yes this is a known bug with all current 1.2.x images. 

A hotfix for this is available in the "latest" version of this image. The problem exists only during installation. Just use Firefox to install and use with any browser you want after that. Alternatively you can test the "latest" image. 

Feel free to post here if you get some further problems with this image.

**Comment by Giovenale2** [comment]
Thx for the quick reply. 
I have tried what you suggested, but with only small results. Trying different borwsers did not solve it for me. trying the latest release, instead allowed some steps further, untill the creation of the db. Once I have confimred the db specifications, and after trying for a while, I get a gateway time out. In my humhub logs I see "open() "/var/www/localhost/htdocs/css/bootstrap.min.css" failed". I assume this is normal at first setup, but it is the only error if find it the humhub logs. 
This is independent of browsers, OS, or mariadb container releases.  
I am a little lost at this point, although it feels like I am 1 step away from a working system.
Thanks.

**Comment by mriedmann** [comment]
The "open() "/var/www/localhost/htdocs/css/bootstrap.min.css" failed" log entry pops up on every 1.2.x installation I tested. As you can see [here](https://github.com/humhub/humhub/blob/45d3f273a2546c0afd1cd8c0627d77591bc7e626/protected/humhub/modules/installer/views/layouts/main.php#L20) here is a link to this file but it does not exists in the actual repo and is not used elsewhere. Maybe it is a leftover from some previous changes. I filed an issue (https://github.com/humhub/humhub/issues/3146) at the official Humhub Repo, hopefully this will be fixed in the next release. 

**To your problem:**
According to your last post I assume you are not using docker-compose, am I right? I have no experience with docker on synology at all so maybe you have to provide some additional information about the parameters you are using.

To start the container without docker-compose you have to have a compatible mariadb/mysql instance somewhere. Please check that a database for humhub exists and the user you are going to use has full rights on this database.

Because this scenario is a bit experimental I recommend using the "latest" tag without any arguments. If this works, try to add volumes or other settings. Come back here if you need some further help.

**Comment by mriedmann** [comment]
Closing because the new release should solve this. Please feel free to open a new issue if this problem still exists with version 1.2.6
