### ISSUE TITLE
Any reason we are saying " Using this in production is possible, but not recommended."

### ISSUE THREAD

**Issue by pandeybk** [mriedmann/humhub-docker#61]
Curious what are the limitation, its working perfectly fine in localhost. I am thinking about using this docker image in kubernetes cluster. Mount persistent volume for storage and use aws rds as mysql backend.

**Comment by mriedmann** [comment]
The sole purpose of this statement is to make people aware that this is not the official recommended way to deploy humhub. Beside this I have not designed this image with scale-out in mind. So the bootup script do not contain any concurrency checks/locks and may cause problems when used in rolling deployments. Another thing is that I did not test load-balanced scenarios. 

It would be a very interesting experiment testing this on k8s and should work with a single pod, recreate setup with persistent storage. Nethertheless, I suggest thinking twice before using this in production because you really want to have a controlled stack and a solid backup/restore strategy.

If you do use this on k8s it would be very nice to share you config. Also, if you hit any problems feel free to open an issue here.

Cheers.

**Comment by pandeybk** [comment]
make sense. I am trying to create helm chart based on this docker image. Somehow I keep seeing following error message,

```
==
No existing installation found!
Installing source files...
'/usr/src/humhub/protected/config/README.md' -> '/var/www/localhost/htdocs/protected/config/README.md'
'/usr/src/humhub/protected/config/common.php' -> '/var/www/localhost/htdocs/protected/config/common.php'
'/usr/src/humhub/protected/config/console.php' -> '/var/www/localhost/htdocs/protected/config/console.php'
'/usr/src/humhub/protected/config/messages/.gitignore' -> '/var/www/localhost/htdocs/protected/config/messages/.gitignore'
'/usr/src/humhub/protected/config/messages' -> '/var/www/localhost/htdocs/protected/config/messages'
'/usr/src/humhub/protected/config/web.php' -> '/var/www/localhost/htdocs/protected/config/web.php'
'/usr/src/humhub/.version' -> '/var/www/localhost/htdocs/protected/config/.version'
Setting permissions...
nc: bad address 'db'
Waiting for database connection...
nc: bad address 'db'
Waiting for database connection...
nc: bad address 'db'
Waiting for database connection...
nc: bad address 'db'
Waiting for database connection...
nc: bad address 'db'
Waiting for database connection...
```

I think its trying to use default db connection instead of reading env variables values,

```
 printenv | grep HUMHUB
GG_SOCIAL_STAGE_HUMHUB_SERVICE_PORT_HTTP=80
GG_SOCIAL_STAGE_HUMHUB_SERVICE_HOST=100.69.214.23
GG_SOCIAL_STAGE_HUMHUB_PORT=tcp://100.69.214.23:80
GG_SOCIAL_STAGE_HUMHUB_SERVICE_PORT=80
GG_SOCIAL_STAGE_HUMHUB_PORT_80_TCP_ADDR=100.69.214.23
HUMHUB_DB_PASSWORD=somepassword
GG_SOCIAL_STAGE_HUMHUB_PORT_80_TCP_PORT=80
HUMHUB_DB_HOST=some-host:3306
GG_SOCIAL_STAGE_HUMHUB_PORT_80_TCP_PROTO=tcp
HUMHUB_DB_USER=someuser
GG_SOCIAL_STAGE_HUMHUB_PORT_80_TCP=tcp://100.69.214.23:80
HUMHUB_DB_NAME=somedbname
```

**Comment by mriedmann** [comment]
Thank you for pointing out this problem! I pushed a fix to the latest tag an hour ago. Please report back if it is working as expected.

**Comment by pandeybk** [comment]
Its working thank you

**Comment by francoisauclair911** [comment]
@pandeybk  would you mind sharing your helm chart if possible?

Thanks
